#### Introducing NumPy Arrays

In [1]:
a = [1,2,3,4,5]
b = [10,11,12,13,14]

In [2]:
# Concatenates two lists `a` and `b` to create a single list containing all elements from both lists
a + b 

[1, 2, 3, 4, 5, 10, 11, 12, 13, 14]

In [3]:
# Iterates over pairs of elements from lists `a` and `b` using zip, adds each pair, and stores the results in a new list `result`

result = []
for first, second in zip(a,b):
    result.append( first + second)

result

[11, 13, 15, 17, 19]

#### Using NumPy for element-wise addition of arrays provides better performance and cleaner code compared to iterating through lists and performing operations manually.

In [4]:
import numpy as np 

In [5]:
# Creates a NumPy array `a` and checks its type, which will return <class 'numpy.ndarray'>, 

a = np.array([1,2,3,4])
type(a)

numpy.ndarray

In [6]:
# Accesses the `dtype` attribute of the NumPy array `a` to return the data type of the elements in the array.
a.dtype

dtype('int32')

In [7]:
f =np.array([1.2,1.3,1.4,1.5])
f.dtype

dtype('float64')

In [8]:
# Accesses the first element of the NumPy array `a`. 
a[0]

1

In [9]:
# Modifies the first element of the NumPy array `a` by assigning it a new value, `10`.
a[0] = 10 
a

array([10,  2,  3,  4])

In [10]:
# However, if you add a float value to an integer-type array, the float will be **truncated** 
# (not rounded), and only the integer part will be stored, effectively treating the result as an integer.
a[0] = 11.5
a

array([11,  2,  3,  4])

In [11]:
# Accesses the `ndim` attribute of the NumPy array `a`, which returns the number of dimensions (axes) of the array.
a.ndim

1

In [12]:
# Accesses the `shape` attribute of the NumPy array `a`, which returns a tuple representing the dimensions of the array.
# For a one-dimensional array like `a`, it will return `(4,)`, indicating that it has 4 elements along a single axis.
a.shape

(4,)

In [13]:
# Accesses the `size` attribute of the NumPy array `a`, which returns the total number of elements in the array.
# For the array `a`, it will return `4` since there are 4 elements in total.
a.size

4

#### 📘 Mathematical Operations on NumPy Arrays


##### NumPy allows you to perform fast and efficient element-wise mathematical operations on arrays.
##### These operations can involve two arrays (of the same shape or broadcastable shapes), 
#####  or an array and a scalar value.
##### 
#####  🔹 Element-wise operations:
#####     - Addition:         a + b         → Adds corresponding elements of arrays a and b
#####     - Subtraction:      a - b         → Subtracts elements of b from elements of a
#####     - Multiplication:   a * b         → Multiplies corresponding elements
#####     - Division:         a / b         → Divides elements of a by elements of b
#####     - Exponentiation:   a ** b        → Raises elements of a to the powers in b

In [14]:
# Performs element-wise addition between two NumPy arrays `a` and `f`.
# Both arrays must have the same shape, or be broadcastable to the same shape, for the operation to work.
# The result is a new array where each element is the sum of the corresponding elements from `a` and `f`.
a + f

array([12.2,  3.3,  4.4,  5.5])

In [15]:
# Performs element-wise multiplication between two NumPy arrays `a` and `f`.
# Each element in the resulting array is the product of the corresponding elements in `a` and `f`.
# This requires that `a` and `f` have the same shape or are broadcastable.
a * f

array([13.2,  2.6,  4.2,  6. ])

In [16]:
# Performs element-wise division between the NumPy arrays `a` and `f`.
# Each element in the resulting array is the result of dividing the corresponding element in `a` by the one in `f`.
# If `f` contains any zeros, NumPy will return `inf` or `nan` and may issue a runtime warning.
a / f 

array([9.16666667, 1.53846154, 2.14285714, 2.66666667])

In [17]:
# Performs element-wise exponentiation between the NumPy arrays `f` and `a`.
# Each element in the resulting array is calculated as `f[i]` raised to the power of `a[i]` (i.e., `f[i] ** a[i]`).
# Both arrays must have the same shape or be broadcastable for this operation to work.
f**a

array([7.43008371, 1.69      , 2.744     , 5.0625    ])

In [18]:
# Multiplies every element in the NumPy array `a` by 10 using element-wise scalar multiplication.
# The result is a new array where each element of `a` is scaled by a factor of 10.
a * 10 

array([110,  20,  30,  40])

# ---------------------------------------------------------------------
#### ⚙️ NumPy Universal Functions (ufuncs)
# ---------------------------------------------------------------------
##### Universal functions, or ufuncs, are vectorized wrappers for simple functions 
##### that operate on NumPy arrays element-wise. They are highly optimized in C 
##### for performance and allow you to perform operations without writing explicit loops.
#
##### 🔹 Key Characteristics:
#####   - Fast: Avoids Python loops and uses low-level optimizations.
#####   - Element-wise: Works on each element of an array independently.
#####   - Supports broadcasting: Works even when array shapes are different but compatible.
#####   - Supports scalar and array inputs.
#
##### 🔹 Examples of Common ufuncs:
#####   ➤ Arithmetic:
#####     - np.add(a, b)         → Adds elements (same as `a + b`)
#####     - np.subtract(a, b)    → Subtracts elements (same as `a - b`)
#####     - np.multiply(a, b)    → Multiplies elements (same as `a * b`)
#####     - np.divide(a, b)      → Divides elements (same as `a / b`)
#####     - np.power(a, b)       → Raises `a` to the power of `b` (same as `a ** b`)
#####
#####   ➤ Trigonometric:
#####     - np.sin(a), np.cos(a), np.tan(a)
#####
#####   ➤ Exponentials & Logarithms:
#####     - np.exp(a)            → Exponential (e^a)
#####     - np.log(a)            → Natural log (ln)
#####     - np.log10(a)          → Log base 10
#####
#####   ➤ Aggregation (reductions):
#####     - np.sum(a), np.mean(a), np.max(a), np.min(a), np.std(a), np.var(a)
#
#####   ➤ Comparison:
#####     - np.equal(a, b), np.greater(a, b), np.less_equal(a, b)
#
##### 🔹 Benefit:
#####   ufuncs make mathematical operations on arrays both **concise** and **efficient**.

#
#### Universal functions are a cornerstone of numerical computing with NumPy.
# ---------------------------------------------------------------------


In [19]:
# Applies the NumPy universal function `np.sqrt()` to the array `a`.
# This calculates the **square root** of each element in `a` individually (element-wise).
# The result is a new array where each element is the square root of the corresponding element in `a`.
# Note: All elements in `a` should be non-negative, or the result will include `nan` or complex numbers
np.sqrt(a)

array([3.31662479, 1.41421356, 1.73205081, 2.        ])

In [20]:
import warnings

In [21]:
import warnings
warnings.filterwarnings("ignore")

In [22]:
b = np.array([1,2,-2]) # An example with with negative element -2
np.sqrt(b)

array([1.        , 1.41421356,        nan])

In [23]:
# Applies the NumPy universal function `np.sin()` to the array `a`.
# This calculates the **sine** of each element in `a` individually (element-wise), 
# where the values in `a` are assumed to be in **radians**.
# The result is a new array where each element is the sine of the corresponding element in `a`.
# Note: If `a` contains values in degrees, you should first convert them to radians 
# using `np.radians(a)` before applying `np.sin()`.
np.sin(a)

array([-0.99999021,  0.90929743,  0.14112001, -0.7568025 ])

In [24]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

#### Setting Array Elements 

#### Array indexing 

In [25]:
# You can access elements at a given position in a NumPy array using the square brackets notation, 
# similar to Python lists. For example, `a[0]` accesses the first element of the array `a`.
# Additionally, like Python lists, NumPy arrays are **mutable sequences**, meaning that 
# you can modify their elements directly. In this case, `a[0] = 0` updates the first element of the array to 0.
# This flexibility allows you to change values at any index in the array, unlike immutable sequences such as tuples.
a[0]

0

#### Beware of type coercion 

In [ ]:
# NumPy enforces **data type consistency** within arrays. Each array has a specific **dtype** 
# (data type) that determines what kind of values it can store. If you try to insert a value 
# that doesn’t match the dtype, NumPy will attempt to convert it.
# 
# For example, if we have an integer array and try to insert a float, NumPy will **truncate** 
# the float to fit the integer type. Conversely, if we have a float array and insert an integer, 
# the integer will be **automatically promoted** to a float to maintain consistency.
# 
# This ensures that operations on NumPy arrays remain efficient and predictable, as the data type 
# of elements is always known and managed. 

a[0] = 10.6
a


array([10,  1,  2,  3])

In [27]:
# fill has the same behavior 

# The `fill()` method in NumPy arrays sets all elements of the array to a specified value.
# In this case, `a.fill(-4.8)` fills the entire array `a` with the value `-4.8`.
# It has the same behavior as setting all elements of the array to a single value, 
# and it maintains the array's data type. If the array's dtype is integer, 
# the floating-point value `-4.8` will be truncated to `-4` to match the integer type.


a.fill(-4.8)
a

array([-4, -4, -4, -4])