#### Multi-Dimensional Arrays

##### Multi-dimensional arrays are structured collections of data organized in multiple dimensions, such as rows and columns in a matrix, enabling efficient storage and manipulation of complex data.

In [47]:
import numpy as np 

In [48]:
a = np.array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [49]:
# a.shape returns (2, 4), which means:
# - The array has 2 rows
# - Each row contains 4 columns
# In other words, it's a 2D array with dimensions 2x4.
a.shape

(2, 4)

In [50]:
# a.size returns 8, which is the total number of elements in the array.
# It's calculated as the product of the number of rows and columns: 2 * 4 = 8.
a.size

8

In [51]:
# a.ndim returns 2, meaning the array is two-dimensional (2D).
# It has both rows and columns.
a.ndim

2

### Indexing And Slicing 

#### Get / Set Element

##### For example:
##### - Getting: a[1, 3] → returns the current value at that position.
##### - Setting: a[1, 3] = -1 → updates the value at that position to -1.

In [52]:
# a[1, 3] returns 13.
# This accesses the element at row index 1 (second row) and column index 3 (fourth column).
# So it's the element in the second row and fourth column of the array.
a[1, 3]

13

In [53]:
# a[1, 3] = -1
# This sets the element at row index 1 (second row), column index 3 (fourth column) to -1.
# You can use this same indexing format to get or update a specific element in the array.
a[1,3] = -1 

In [54]:
# a[1] returns the entire second row of the array.
# Since indexing starts at 0, a[1] refers to row index 1 (the second row).
# For example, if a = [[0, 1, 2, 3], [10, 11, 12, 13]], then a[1] returns [10, 11, 12, 13].
a[1]

array([10, 11, 12, -1])

In [55]:
a[:,1]

array([ 1, 11])

#### Slicing  var[start : stop : step]

##### Slicing is a technique used to extract specific portions of an array by specifying start, stop, and step indices for rows, columns, or both, allowing efficient access to subarrays without copying data.

In [56]:
#             -5,-4,-3,-2,-1
#indices       0, 1, 2, 3, 4

a = np.array([10,11,12,13,14])

#### Slicing Arrays

In [57]:
# return only 11 12

a[1:3]

array([11, 12])

In [58]:
# negative indices work also 

# a[1:-2] returns [11, 12]
# - The starting index '1' refers to the element at index 1, which is 11.
# - The '-2' index means "up to but not including the second-to-last element" (which is 13).
# This effectively slices the array to get elements from index 1 to index 2, resulting in [11, 12].


a[1:-2]

array([11, 12])

In [59]:
# a[-4:3] slices the array from the fourth-to-last element (-4) to index 3 (inclusive).
# While it works, it's generally not recommended because:
# - Using negative indices with positive indices can lead to confusion.
# - It's harder to read and understand, especially for others or when revisiting the code later.
# As Alex Chabot-Leclerc advises: "Be kind and don't do that!" 
# It's better to stick to clear, straightforward indexing for readability and maintainability.
a[-4:3] 

array([11, 12])

#### Omitting indices in slicing means the boundaries are assumed to be the beginning or end of the array.


In [60]:
# Grab the first 3 elements 
a[:3]

array([10, 11, 12])

In [61]:
# grab the last 2 elements 
a[-2:]

array([13, 14])

In [62]:
# - start and stop are omitted, so it starts from the beginning and goes to the end.
# - step is 2, meaning it takes every second element.
# Example: if a = np.array([10, 11, 12, 13, 14]), then a[::2] returns [10, 12, 14].
a[::2]

array([10, 12, 14])

#### Practice Slicing 

In [63]:
arr = np.array([
    [0, 1, 2, 3, 4, 5],
    [10, 11, 12, 13, 14, 15],
    [20, 21, 22, 23, 24, 25],
    [30, 31, 32, 33, 34, 35],
    [40, 41, 42, 43, 44, 45],
    [50, 51, 52, 53, 54, 55]
])
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

##### Using slicing, how can you extract only the elements 3 and 4 from the array?

In [64]:
arr[0, 3:5]

array([3, 4])

#### Using slicing, how can you extract the following subarray? The expected result is:  array([[44, 45],[54, 55]])




In [65]:
arr[4: , 4:] 

array([[44, 45],
       [54, 55]])

#### Extract all the values from the third column The expected result is : array([ 2, 12, 22, 32, 42, 52])

In [66]:
arr[:, 2]

array([ 2, 12, 22, 32, 42, 52])

#### Using slicing, extract the even-indexed columns from rows 2 and 4 only. The expected result is: array([[20, 22, 24] [40, 42, 44]])



In [67]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [68]:
arr[2:5:2,::2]

array([[20, 22, 24],
       [40, 42, 44]])