#### Operations on the Array Structure

##### Operations that only affect the array structure not the data can usually be executed without copying memory

In [1]:
import numpy as np

a = np.arange(6)
a # Six Elements 

array([0, 1, 2, 3, 4, 5])

#### This is not a new copy of the data. The original data does not get reordered 

In [2]:
# 
b = a.reshape(2, 3)
b # Three Columns and Two Rows 

array([[0, 1, 2],
       [3, 4, 5]])

##### Transpose 

In [3]:
# Transpose
a = np.array([[0,1,2],
             [3,4,5]])
a.shape # 2 Rows , 3 Columns 

(2, 3)

#### Transpose swaps the order of axes 

In [4]:
a.T # will make it 3 rows , 2 columns 

array([[0, 3],
       [1, 4],
       [2, 5]])

In [5]:
a.T.shape

(3, 2)

#### Transpose returns view 

##### Transpose does not move values around in memory. It only changes the order of " Strides " in the array

In [6]:
a.strides

(12, 4)

In [7]:
a.T.strides

(4, 12)

#### Reshaping Arrays

In [8]:
a = np.array([[0,1,2],
             [3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
# Return a new array with a different shape (a view where possible)
a.reshape(3,2)


array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
# Reshape cannot change the number of elements in an array 
a.reshape(4,2) 

### ValueError : total size of new array must be unchanged 

ValueError: cannot reshape array of size 6 into shape (4,2)

In [ ]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.shape

(6,)

In [ ]:
# Reshape array in place to 2x3

a.shape= (2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

#### Flattening Arrays 

#### Flatten (Safe)

In [ ]:
# a.flatten() convert a multi-dimensional array into 1-D Array. The new array is a copy of the original data
# create a 2D Array
a = np.array([[0,1],
              [2,3]])
a

array([[0, 1],
       [2, 3]])

In [ ]:
# Flatten out elements to 1D
b = a.flatten()
b

array([0, 1, 2, 3])

In [ ]:
# Changing b does not change 1 
b[0] = 10
b

array([10,  1,  2,  3])

In [ ]:
a


array([[0, 1],
       [2, 3]])

#### Ravel (efficient)

In [12]:
# a.ravel() is the same as a.flatten(), but returns a reference or view of the array if possible (i.e the memory is contiguous). Otherwise the new array copies the data 
# Flatten out elements to 1D 

b = a.ravel()
b

array([0, 1, 2, 3, 4, 5])

In [13]:
# Changing b does change a 

b[0] = 10
b

array([10,  1,  2,  3,  4,  5])

In [14]:
a

array([[10,  1,  2],
       [ 3,  4,  5]])