In [1]:
import numpy as np
from numpy import loadtxt


In [2]:
data_wind = loadtxt('./wind_statistics/wind.data')

In [3]:
data_wind

array([[61.  ,  1.  ,  1.  , ..., 12.58, 18.5 , 15.04],
       [61.  ,  1.  ,  2.  , ...,  9.67, 17.54, 13.83],
       [61.  ,  1.  ,  3.  , ...,  7.67, 12.75, 12.71],
       ...,
       [78.  , 12.  , 29.  , ..., 16.42, 18.88, 29.58],
       [78.  , 12.  , 30.  , ..., 12.12, 14.67, 28.79],
       [78.  , 12.  , 31.  , ..., 11.38, 12.08, 22.08]])

In [53]:
dates = data_wind[: , :3]
dates

array([[61.,  1.,  1.],
       [61.,  1.,  2.],
       [61.,  1.,  3.],
       ...,
       [78., 12., 29.],
       [78., 12., 30.],
       [78., 12., 31.]])

##### The first three columns are year, month and day.  The remaining 12 columns are average windspeeds in knots at 12 locations in Ireland on tha day.

In [45]:
data = data_wind[: , 3:]
data

array([[15.04, 14.96, 13.17, ..., 12.58, 18.5 , 15.04],
       [14.71, 16.88, 10.83, ...,  9.67, 17.54, 13.83],
       [18.5 , 16.88, 12.33, ...,  7.67, 12.75, 12.71],
       ...,
       [14.  , 10.29, 14.42, ..., 16.42, 18.88, 29.58],
       [18.5 , 14.04, 21.29, ..., 12.12, 14.67, 28.79],
       [20.33, 17.41, 27.29, ..., 11.38, 12.08, 22.08]])

#### 2. Calculate the min, max and mean windspeeds and standard deviation of the windspeeds over all the locations and all the times (a single set of numbers for the entire dataset).

In [5]:
min = data.min()
min


0.0

In [6]:
max = data.max()
max

42.54

In [7]:
mean = data.mean()
mean

10.22837377040868

In [8]:
Standard_div = data.std()
Standard_div

5.603840181095793

#### 3. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days (a different set of numbers for each location)

In [9]:
min = data.min(axis= 0)
min

array([0.67, 0.21, 1.5 , 0.  , 0.13, 0.  , 0.  , 0.  , 0.  , 0.04, 0.13,
       0.67])

In [10]:
max = data.max(axis= 0)
max

array([35.8 , 33.37, 33.84, 28.46, 37.54, 26.16, 30.37, 31.08, 25.88,
       28.21, 42.38, 42.54])

In [11]:
mean = data.mean(axis= 0)
mean

array([12.36371463, 10.64644813, 11.66010344,  6.30627472, 10.45688013,
        7.09225434,  9.7968345 ,  8.49442044,  8.49581838,  8.70726803,
       13.121007  , 15.59946152])

In [12]:
standard_div = data.std(axis = 0)
standard_div

array([5.61918301, 5.26820081, 5.00738377, 3.60513309, 4.93536333,
       3.96838126, 4.97689374, 4.49865783, 4.16746101, 4.50327222,
       5.83459319, 6.69734719])

#### 4. Calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day (a different set of numbers for each day)

In [13]:
min = data.min(axis= 1)
min

array([9.29, 6.5 , 6.17, ..., 8.71, 9.13, 9.59])

In [14]:
max = data.max(axis = 1)
max

array([18.5 , 17.54, 18.5 , ..., 29.58, 28.79, 27.29])

In [15]:
mean = data.mean(axis = 1)
mean

array([13.09666667, 11.79833333, 11.34166667, ..., 14.89      ,
       15.3675    , 15.4025    ])

In [16]:
standard_div = data.std(axis= 1)
standard_div

array([2.5773188 , 3.28972854, 3.50543348, ..., 5.51175108, 5.30456427,
       5.45971172])

#### 5. Find the location which has the greatest windspeed on each day (an integer column number for each day).

In [56]:
greatest_windspeed = data.argmax(axis=1)
greatest_windspeed

array([10, 10,  0, ..., 11, 11,  2], dtype=int64)

#### 6. Find the year, month and day on which the greatest windspeed was recorded.


In [57]:
daily_max = data.max(axis=1)
max_row = daily_max.argmax()
max_row, max_col = np.where(data == data.max())
max_row, max_col = np.unravel_index(data.argmax(), data.shape)



In [21]:
year = data_wind[max_row,0]
year

array([66.])

In [22]:
month = data_wind[max_row,1]
month

array([12.])

In [64]:
day = data_wind[max_row, 2]
day 

2.0

#### 7. Find the average windspeed in January for each location.


In [24]:
January_ind = data_wind[:, 1] == 1
January_ind

array([ True,  True,  True, ..., False, False, False])

In [25]:
January_data = data[January_ind]
January_data

array([[15.04, 14.96, 13.17, ..., 12.58, 18.5 , 15.04],
       [14.71, 16.88, 10.83, ...,  9.67, 17.54, 13.83],
       [18.5 , 16.88, 12.33, ...,  7.67, 12.75, 12.71],
       ...,
       [29.38, 18.54, 28.08, ..., 20.5 , 19.12, 38.2 ],
       [ 9.62,  8.71,  9.59, ...,  4.46, 10.41, 12.83],
       [10.5 ,  8.79,  9.54, ...,  6.38,  6.54, 17.37]])

In [26]:
mean_january = January_data.mean()
mean_january

11.793809737156511

#### Bonus Bonus : this is really tricky...


##### 1. Calculate the mean windspeed for each month in the dataset.  Treat January 1961 and January 1962 as *different* months. (hint: first find a way to create an identifier unique for each month. The second step might require a for loop.)

In [42]:
# Create a unique month index 
months = (data_wind[:, 0] - 61) * 12 + data_wind[:, 1] - 1
months

array([  0.,   0.,   0., ..., 215., 215., 215.])

In [43]:
# Step 2: Calculate mean windspeed per day (across all 12 stations)
daily_means = data.mean(axis=1)
daily_means

array([13.09666667, 11.79833333, 11.34166667, ..., 14.89      ,
       15.3675    , 15.4025    ])

In [44]:
unique_months = np.unique(months)  # All unique month indices
monthly_means = []

for m in unique_months:
    mask = months == m  # Boolean mask for the current month
    winds_for_month = daily_means[mask]  # Windspeeds for the current month
    mean_wind = winds_for_month.mean()  # Calculate the mean for this month
    monthly_means.append((m, mean_wind))

monthly_means

[(0.0, 11.380645161290323),
 (1.0, 13.492351190476189),
 (2.0, 11.07236559139785),
 (3.0, 8.411166666666666),
 (4.0, 8.973413978494627),
 (5.0, 9.698277777777777),
 (6.0, 9.019112903225807),
 (7.0, 10.787446236559141),
 (8.0, 9.98913888888889),
 (9.0, 11.476586021505378),
 (10.0, 8.972749999999998),
 (11.0, 10.83540322580645),
 (12.0, 12.132123655913977),
 (13.0, 13.595982142857144),
 (14.0, 9.184596774193547),
 (15.0, 10.118583333333332),
 (16.0, 10.238091397849464),
 (17.0, 10.377111111111107),
 (18.0, 8.553924731182796),
 (19.0, 10.162473118279571),
 (20.0, 9.032333333333334),
 (21.0, 8.77284946236559),
 (22.0, 8.699583333333331),
 (23.0, 13.504247311827957),
 (24.0, 11.398306451612903),
 (25.0, 12.197499999999996),
 (26.0, 12.226801075268817),
 (27.0, 11.666972222222224),
 (28.0, 11.92016129032258),
 (29.0, 9.583972222222224),
 (30.0, 7.977930107526881),
 (31.0, 10.626236559139784),
 (32.0, 9.614694444444444),
 (33.0, 11.988736559139786),
 (34.0, 12.01725),
 (35.0, 11.7037634408602