In [41]:
import numpy as np
from numpy import loadtxt


In [42]:
data_wind = loadtxt('./wind_statistics/wind.data')

In [43]:
data_wind

array([[61.  ,  1.  ,  1.  , ..., 12.58, 18.5 , 15.04],
       [61.  ,  1.  ,  2.  , ...,  9.67, 17.54, 13.83],
       [61.  ,  1.  ,  3.  , ...,  7.67, 12.75, 12.71],
       ...,
       [78.  , 12.  , 29.  , ..., 16.42, 18.88, 29.58],
       [78.  , 12.  , 30.  , ..., 12.12, 14.67, 28.79],
       [78.  , 12.  , 31.  , ..., 11.38, 12.08, 22.08]])

##### The first three columns are year, month and day.  The remaining 12 columns are average windspeeds in knots at 12 locations in Ireland on tha day.

In [44]:
data = data_wind[: , 3:]
data

array([[15.04, 14.96, 13.17, ..., 12.58, 18.5 , 15.04],
       [14.71, 16.88, 10.83, ...,  9.67, 17.54, 13.83],
       [18.5 , 16.88, 12.33, ...,  7.67, 12.75, 12.71],
       ...,
       [14.  , 10.29, 14.42, ..., 16.42, 18.88, 29.58],
       [18.5 , 14.04, 21.29, ..., 12.12, 14.67, 28.79],
       [20.33, 17.41, 27.29, ..., 11.38, 12.08, 22.08]])

#### 2. Calculate the min, max and mean windspeeds and standard deviation of the windspeeds over all the locations and all the times (a single set of numbers for the entire dataset).

In [45]:
min = data.min()
min


0.0

In [46]:
max = data.max()
max

42.54

In [47]:
mean = data.mean()
mean

10.22837377040868

In [48]:
Standard_div = data.std()
Standard_div

5.603840181095793

#### 3. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days (a different set of numbers for each location)

In [49]:
min = data.min(axis= 0)
min

array([0.67, 0.21, 1.5 , 0.  , 0.13, 0.  , 0.  , 0.  , 0.  , 0.04, 0.13,
       0.67])

In [50]:
max = data.max(axis= 0)
max

array([35.8 , 33.37, 33.84, 28.46, 37.54, 26.16, 30.37, 31.08, 25.88,
       28.21, 42.38, 42.54])

In [51]:
mean = data.mean(axis= 0)
mean

array([12.36371463, 10.64644813, 11.66010344,  6.30627472, 10.45688013,
        7.09225434,  9.7968345 ,  8.49442044,  8.49581838,  8.70726803,
       13.121007  , 15.59946152])

In [52]:
standard_div = data.std(axis = 0)
standard_div

array([5.61918301, 5.26820081, 5.00738377, 3.60513309, 4.93536333,
       3.96838126, 4.97689374, 4.49865783, 4.16746101, 4.50327222,
       5.83459319, 6.69734719])

#### 4. Calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day (a different set of numbers for each day)

In [53]:
min = data.min(axis= 1)
min

array([9.29, 6.5 , 6.17, ..., 8.71, 9.13, 9.59])

In [54]:
max = data.max(axis = 1)
max

array([18.5 , 17.54, 18.5 , ..., 29.58, 28.79, 27.29])

In [55]:
mean = data.mean(axis = 1)
mean

array([13.09666667, 11.79833333, 11.34166667, ..., 14.89      ,
       15.3675    , 15.4025    ])

In [56]:
standard_div = data.std(axis= 1)
standard_div

array([2.5773188 , 3.28972854, 3.50543348, ..., 5.51175108, 5.30456427,
       5.45971172])

#### 5. Find the location which has the greatest windspeed on each day (an integer column number for each day).

In [57]:
greatest_windspeed = data.argmax(axis= 1)
greatest_windspeed

array([10, 10,  0, ..., 11, 11,  2], dtype=int64)

#### 6. Find the year, month and day on which the greatest windspeed was recorded.


In [58]:
daily_max = data.max(axis=1)
max_row = daily_max.argmax()
max_row, max_col = np.unravel_index(data.argmax(), data.shape)
max_row, max_col = where(data == data.max())



In [59]:
year = data_wind[max_row,0]
year

array([66.])

In [61]:
month = data_wind[max_row,1]
month

array([12.])

In [64]:
day = data_wind[max_row, 2]
day 

array([2.])

#### 7. Find the average windspeed in January for each location.


In [66]:
January_ind = data_wind[:, 1] == 1
January_ind

array([ True,  True,  True, ..., False, False, False])

In [68]:
January_data = data[January_ind]
January_data

array([[15.04, 14.96, 13.17, ..., 12.58, 18.5 , 15.04],
       [14.71, 16.88, 10.83, ...,  9.67, 17.54, 13.83],
       [18.5 , 16.88, 12.33, ...,  7.67, 12.75, 12.71],
       ...,
       [29.38, 18.54, 28.08, ..., 20.5 , 19.12, 38.2 ],
       [ 9.62,  8.71,  9.59, ...,  4.46, 10.41, 12.83],
       [10.5 ,  8.79,  9.54, ...,  6.38,  6.54, 17.37]])

In [70]:
mean_january = January_data.mean()
mean_january

11.793809737156511